### ISSUE TITLE
wrong: no player's name back ‘null'!

### ISSUE THREAD

**Issue by Noogear** [SkinsRestorer/SRPlaceholderAPIExpansion#20]
[08:48:20 警告]: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "skinName" is null
[08:48:20 警告]: 	at SkinsRestorer.jar//net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:171)
[08:48:20 警告]: 	at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerAPI.getSkinData(SkinsRestorerAPI.java:135)
[08:48:20 警告]: 	at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerAPI.getSkinTextureUrl(SkinsRestorerAPI.java:199)
[08:48:20 警告]: 	at com.extendedclip.papi.expansion.skinsrestorer.SRWrapper.getSkinTextureUrl(SRWrapper.java:21)
[08:48:20 警告]: 	at com.extendedclip.papi.expansion.skinsrestorer.SkinsRestorerExpansion.getSkinTextureUrl(SkinsRestorerExpansion.java:82)
[08:48:20 警告]: 	at com.extendedclip.papi.expansion.skinsrestorer.SkinsRestorerExpansion.onRequest(SkinsRestorerExpansion.java:75)
[08:48:20 警告]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[08:48:20 警告]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[08:48:20 警告]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java

**Comment by Noogear** [comment]
every papi will be back ’null‘ not the 'alex','steve',empty or their name!

**Comment by Noogear** [comment]
it also will be happened after people cmd: skin clear

**Comment by xknat** [comment]
Thanks, will pick this up

**Comment by Noogear** [comment]
Really need it. Looking forward to your update! :)

**Comment by xknat** [comment]
Resolved in https://github.com/SkinsRestorer/SRPlaceholderAPIExpansion/releases/tag/1.7.2

**Comment by Noogear** [comment]
thanks, i test it now.

**Comment by Noogear** [comment]
> https://github.com/SkinsRestorer/SRPlaceholderAPIExpansion/releases/tag/1.7.2 中解决

It was not fixed. There was still wrong viewed in console just like above.

**Comment by Noogear** [comment]
[04:30:39 警告]: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "skinName" is null
[04:30:39 警告]: 	at SkinsRestorer.jar//net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:171)
[04:30:39 警告]: 	at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerAPI.getSkinData(SkinsRestorerAPI.java:135)
[04:30:39 警告]: 	at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerAPI.getSkinTextureUrl(SkinsRestorerAPI.java:199)
[04:30:39 警告]: 	at com.extendedclip.papi.expansion.skinsrestorer.SRWrapper.getSkinTextureUrl(SRWrapper.java:21)
[04:30:39 警告]: 	at com.extendedclip.papi.expansion.skinsrestorer.SkinsRestorerExpansion.getSkinTextureUrl(SkinsRestorerExpansion.java:86)
[04:30:39 警告]: 	at com.extendedclip.papi.expansion.skinsrestorer.SkinsRestorerExpansion.onRequest(SkinsRestorerExpansion.java:75)
[04:30:39 警告]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[04:30:39 警告]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[04:30:39 警告]: 	at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)

**Comment by xknat** [comment]
> [04:30:39 警告]: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "skinName" is null [04:30:39 警告]: at SkinsRestorer.jar//net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:171) [04:30:39 警告]: at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerAPI.getSkinData(SkinsRestorerAPI.java:135) [04:30:39 警告]: at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerAPI.getSkinTextureUrl(SkinsRestorerAPI.java:199) [04:30:39 警告]: at com.extendedclip.papi.expansion.skinsrestorer.SRWrapper.getSkinTextureUrl(SRWrapper.java:21) [04:30:39 警告]: at com.extendedclip.papi.expansion.skinsrestorer.SkinsRestorerExpansion.getSkinTextureUrl(SkinsRestorerExpansion.java:86) [04:30:39 警告]: at com.extendedclip.papi.expansion.skinsrestorer.SkinsRestorerExpansion.onRequest(SkinsRestorerExpansion.java:75) [04:30:39 警告]: at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) [04:30:39 警告]: at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) [04:30:39 警告]: at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)

what parameter do you use?

**Comment by Noogear** [comment]
> > [04:30:39 警告]: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "skinName" is null [04:30:39 警告]: at SkinsRestorer.jar//net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:171) [04:30:39 警告]: at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerAPI.getSkinData(SkinsRestorerAPI.java:135) [04:30:39 警告]: at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerAPI.getSkinTextureUrl(SkinsRestorerAPI.java:199) [04:30:39 警告]: at com.extendedclip.papi.expansion.skinsrestorer.SRWrapper.getSkinTextureUrl(SRWrapper.java:21) [04:30:39 警告]: at com.extendedclip.papi.expansion.skinsrestorer.SkinsRestorerExpansion.getSkinTextureUrl(SkinsRestorerExpansion.java:86) [04:30:39 警告]: at com.extendedclip.papi.expansion.skinsrestorer.SkinsRestorerExpansion.onRequest(SkinsRestorerExpansion.java:75) [04:30:39 警告]: at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) [04:30:39 警告]: at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) [04:30:39 警告]: at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
> 
> what parameter do you use?

%skinsrestorer_getTextureID_Or_PlayerName%, %skinsrestorer_getTextureID_Or_Alex% and %skinsrestorer_getTextureID_Or_Empty%. I tested them one by one but it not worked.

**Comment by Noogear** [comment]
> > [04：30：39 警告]： java.lang.NullPointerException： 无法调用 “String.toLowerCase（）”，因为 “skinName” 为空 [04：30：39 警告]： at SkinsRestorer.jar//net.skinsrestorer.shared.storage.SkinStorage.getSkinData（SkinStorage.java：171） [04：30：39 警告]： at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerAPI.getSkinData（SkinsRestorerAPI.java：135） [04：30：39 警告]： at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerAPI.getSkinTextureUrl（SkinsRestorerAPI.java：199） [04：30：39警告]： at com.extendedclip.papi.expansion.skinsrestorer.SRWrapper.getSkinTextureUrl（SRWrapper.java：21） [04：30：39 警告]： at com.extendedclip.papi.expansion.skinsrestorer.SkinsRestorerExpansion.getSkinTextureUrl（SkinsRestorerExpansion.java：86） [04：30：39 警告]： at com.extendedclip.papi.expansion.skinsrestorer.SkinsRestorerExpansion.onRequest（SkinsRestorerExpansion.java：75） [04：30：39 警告]： at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply（CharsReplacer.java：119） [04：30：39 警告]： at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders（PlaceholderAPI.java：71） [04：30：39 警告]： at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders（PlaceholderAPI.java：99）
> 
> 您使用什么参数？

Could it be changed to directly output the %player_name% when the player is not using a custom skin by the skinsrestorer?

**Comment by Noogear** [comment]
when I used %skinsrestorer_getTextureID_Or_Null, it also viewed wrong like above.

**Comment by xknat** [comment]
> when I used %skinsrestorer_getTextureID_Or_Null, it also viewed wrong like above.

**Or_Null** will return null, your not handeling the null so it will throw a nullpointer

**Comment by Noogear** [comment]
> > when I used %skinsrestorer_getTextureID_Or_Null, it also viewed wrong like above.
> 
> **Or_Null** will return null, your not handeling the null so it will throw a nullpointer

I have tested all of them.
But all 'null'

**Comment by xknat** [comment]
> > > when I used %skinsrestorer_getTextureID_Or_Null, it also viewed wrong like above.
> > 
> > 
> > **Or_Null** will return null, your not handeling the null so it will throw a nullpointer
> 
> I have tested all of them. But all 'null'

thanks for feedback, ill look into this.

**Comment by Noogear** [comment]
> 

In my logic, it should first check with SkinRestorer to see if custom skins are set. If not, output the name, otherwise go to skinrestorer to check their costom skin file. But it doesn't look like that at the moment.

Please inform me in time if there is any update, thank you.
